### ISSUE TITLE
Segfault when linking with mxml library

### ISSUE THREAD

**Issue by duttajnu** [michaelrsweet/mxml#294] opened 2022-07-11 10:05 UTC
In last release v3.3, initialization of global data removed from '_MXML_FINI' which is registered as destructor for GNUC, 
```c
#elif defined(__GNUC__) /* Linux and Mac OS X */
#  define _MXML_FINI __attribute((destructor)) _mxml_fini
#else
```
which try to delete the pthread key,
```c
 static void
 _MXML_FINI(void)
 {
   pthread_key_delete(_mxml_key);
 }
```
This causes segfault on the application which exits/terminates before calling any mxml api.

The above mentioned change has been introduced with below commit:
02f3310322e9d6613d17354fa98b297411d6ccf3

**Comment by michaelrsweet** [comment] 2022-07-14 13:06
Treating this as a dupe of #293.

**Closed by michaelrsweet** 2022-07-14 13:06 UTC
Labels: investigating
