### ISSUE TITLE
mxmlDelete not free

### ISSUE THREAD

**Issue by bipbip59** [michaelrsweet/mxml#187] opened 2017-03-28 09:14 UTC
Hello,
If you make this code
`

        mxml_node_t *xml=NULL;    
	mxml_node_t *data=NULL;  
	xml = mxmlNewXML("1.0");
	data = mxmlNewElement(xml,"ARCHIVE");
	data = mxmlNewElement(data, "FTP");
	mxmlDelete(xml);
`
Some nodes are not free. (Checked with codeguard)

For good issue  make this change in mxmlDelete function

`
void mxmlDelete(mxml_node_t *node)		
{
   mxml_node_t	*current;    
	if (!node) return;
  mxmlRemove(node);
   while ((current = node->child)!=NULL)
   {
	  mxmlDelete(current);
   }
  mxml_free(node);
}
`

Enjoy !

**Comment by michaelrsweet** [comment] 2017-03-28 11:19
Dupe of Issue #183.

**Closed by michaelrsweet** 2017-03-28 11:19 UTC

**Comment by michaelrsweet** [comment] 2017-03-28 11:21
(Note that your proposed fix reintroduces recursion which we don't want for security/stack exhaustion reasons)
