### ISSUE TITLE
modify specific item value and save it in the file

### ISSUE THREAD

**Issue by bowen817** [michaelrsweet/mxml#246] opened 2019-02-14 02:02 UTC
Dear michael sweet,

I met an issue during save file. 
My operation is:

```
    FILE *fp = fopen("configuration.xml","r+");
    mxml_node_t *tree = mxmlLoadFile(NULL, fp, MXML_NO_CALLBACK);   
    mxml_node_t *node2 = mxmlFindElement(tree, tree, "node2",NULL,NULL,MXML_DESCEND);
   if(node2) mxmlSetText(node2, 0, "Val3");
   mxmlSaveFile(tree, fp, whitespace_cb);
```

When I run above code, the configuration.xml have two parts, one is original value, the other one is modifed value.  like this:

```
< ? xml version="1.0" encoding="utf-8" ? > 
< data > 
        < node2 > Val2< / node2 > 
< / data >
```

```
< ? xml version="1.0" encoding="utf-8" ? > 
< data > 
       < node2 > Val3 < / node2 > 
< / data >
```

I just need to save modified value in the file. 
Please give me some guidance. thanks in advance!

**Comment by michaelrsweet** [comment] 2019-02-14 03:51
@bowen817 What version of Mini-XML are you using?

What OS?

**Comment by bowen817** [comment] 2019-02-14 06:53
Oh, sorry, mxml version is 3.0, I setup the environment in ubuntu 18.04.1 LTS and Linux version is 4.15.0.

**Comment by michaelrsweet** [comment] 2019-02-17 11:50
OK, the problem is with using the "r+" open mode - you should be opening the file in "r" mode, loading the XML, closing the file, and then reopening with "w" mode to truncate and overwrite. It is not safe to "update" the file in this way since you don't know whether the new file will be same length (or longer).

**Closed by michaelrsweet** 2019-02-17 11:50 UTC
Labels: cannot reproduce
